<a href="https://colab.research.google.com/github/kunalsir98/machine_learning/blob/main/Logisitic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import pandas as pd
import numpy as np
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix

In [25]:
X,y=make_classification(n_samples=1000,n_features=5,random_state=123)

In [26]:
X


array([[ 0.87728113, -0.59642825,  0.44019839, -0.52108094,  0.31432298],
       [ 0.55856502, -0.41451292,  0.813623  , -0.54325372,  0.14734302],
       [-0.90289911,  0.38303337, -0.71157267, -0.86768895, -0.67394137],
       ...,
       [ 1.7713853 , -0.96445461,  0.99337636,  0.40674576,  0.99881985],
       [-1.19977749,  0.48167954,  1.47831033, -1.31903526, -0.93698258],
       [ 0.33976266, -0.29183452, -0.82476815, -0.57191024,  0.02935597]])

In [27]:
y

array([0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,

In [28]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [29]:
X_train.shape

(700, 5)

In [30]:
X_test.shape

(300, 5)

In [31]:
model=LogisticRegression()

In [32]:
##training model

In [33]:
model.fit(X_train,y_train)

LogisticRegression()

In [34]:
model.score(X_train,y_train)

0.9428571428571428

In [35]:
y_pred=model.predict(X_test)

In [37]:
accuracy_score(y_test,y_pred)

0.97

In [38]:
confusion_matrix(y_test,y_pred)

array([[149,   3],
       [  6, 142]])

In [39]:
0.97-0.9428571428571428

0.027142857142857135